fix: add a missed header inclusion (-Wdelete-incomplete)
    src/obconversion.cpp:703:21: error: deleting pointer to incomplete type
          'OBBase' is incompatible with C++2c and may cause undefined behavior [-Wdelete-incomplete]

Signed-off-by: Eisuke Kawashima <e-kwsm@users.noreply.github.com>